import { SOLDIER_RUNTIME_CONFIG } from "../config";
import { createPrototypeStats } from "../stats/soldierStats";
import type { ControllerType, Soldier, SoldierBaseStats, SoldierLoadout, Strategy, Team } from "../types";
import { validateSoldierLoadout } from "../systems/unitLoadoutSystem";

export function createSoldier(
  id: string,
  team: Team,
  controller: ControllerType,
  x: number,
  y: number,
  strategy: Strategy = "melee",
  stats: SoldierBaseStats = createPrototypeStats(),
  loadout?: SoldierLoadout,
): Soldier {
  const applied = loadout ? validateSoldierLoadout(loadout) : null;
  const finalStats = applied?.stats ?? stats;
  return {
    id, unitType: applied?.unitType ?? "PROTOTYPE", technique: applied?.technique ?? "PROTOTYPE_AREA",
    team, controller, strategy, state: "NORMAL", temporaryOrder: null, recoveryGate: null, recoveryGateEntered: false, x, y,
    strategyObjectiveKind: "ANCHOR",
    strategyObjectiveX: x,
    strategyObjectiveY: y,
    engagementStartedAt: null,
    engagementOriginX: null,
    engagementOriginY: null,
    velocityX: 0,
    velocityY: 0,
    baseContactLockTicks: 0,
    avoidanceSide: null,
    avoidanceUntil: 0,
    avoidanceObstacleId: null,
    combatActionState: "IDLE",
    attackStartedAt: null,
    attackHitAt: null,
    attackRecoveryEndsAt: null,
    attackTargetKind: null,
    attackTargetId: null,
    attackHitApplied: false,
    reactionState: "NONE",
    reactionStartedAt: null,
    reactionEndsAt: null,
    knockbackDirectionX: 0,
    knockbackDirectionY: 0,
    knockbackRemainingDistance: 0,
    combatFeedbackMarker: null,
    combatFeedbackUntil: 0,
    specialReadyAt: 0,
    pendingSecondSpecialAt: null,
    combatGauge: 0,
    combatGaugeUpdatedAt: null,
    specialLockUntil: 0,
    abilityActionLockUntil: 0,
    trapStateUntil: 0,
    activeSpecialTechnique: null,
    specialWavesRemaining: 0,
    nextSpecialWaveAt: null,
    specialAbilities: applied ? [...applied.specialAbilities] : [],
    rareSpecialAbilities: applied ? [...(applied.rareSpecialAbilities ?? [])] : [],
    pendingMoutaiSpecials: 0,
    moutaiTriggeredForRetreat: false,
    treatmentUsedSinceLastBaseVisit: false,
    recoveryTargetKind: "BASE_GATE",
    recoveryHealerId: null,
    touchingEnemyFenceIds: [],
    facingX: team === "player" ? 1 : -1,
    facingY: 0,
    aimX: null,
    aimY: null,
    isConfused: false,
    strategistFireZoneUntil: 0,
    ninjaDashUntil: 0,
    ninjaDashStartedAt: null,
    ninjaDashStartX: x,
    ninjaDashStartY: y,
    ninjaDashTargetX: x,
    ninjaDashTargetY: y,
    preferredApproachAngle: null,
    preferredApproachTargetId: null,
    stats: { ...finalStats },
    hp: finalStats.maxHp,
    maxHp: finalStats.maxHp,
    attackRange: SOLDIER_RUNTIME_CONFIG.attackRange,
    attackCooldownMs: SOLDIER_RUNTIME_CONFIG.attackCooldownMs,
    lastAttackAt: -SOLDIER_RUNTIME_CONFIG.attackCooldownMs,
    targetId: null,
    anchorX: x,
    anchorY: y,
    moveTargetX: null,
    moveTargetY: null,
    isDead: false,
  };
}
